# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer
    -   id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
    -   id: check-toml
    -   id: check-added-large-files

-   repo: local
    hooks:
    -   id: linter
        name: linter
        files: ^.*\.py$
        entry: uv run ruff check . --fix --exit-non-zero-on-fix --verbose --config "src=['.']"
        language: system
        always_run: true
    -   id: formatter
        name: formatter
        files: ^.*\.py$
        entry: uv run ruff format . --verbose
        language: system
        always_run: true
